### ISSUE TITLE
Creating loginfiles for cloned accounts overwrites original loginfile

### ISSUE THREAD

**Issue by sn0opy** [TheCheatsrichter/Gw2_Launchbuddy#235]
Cloning an account doesn't seem to update some internal IDs causing Launchbuddy to overwrite the original's loginfile eventhough I hit the re-create button on the cloned version.

Creating each account one by one does properly create the loginfile for each of them.

**Comment by TheCheatsrichter** [comment]
Tested and found the issue:
Cloned accounts do hold the same reference af the origin account and therefore are "synched". Fix will be made in an upcoming patch.

**Comment by Lego6245** [comment]
Maybe we could split the concept of "accounts" away from "settings". Create an account, and then use that account with multiple distinct profiles (i.e. a profile for playing, a profile for alt logging, etc). Then you could set up your accounts like normal, and then, instead of having a distinct loginfile for each account, you just have the singular loginfile for the account, and then apply whatever distinct profile to it that you desire.

**Comment by TheCheatsrichter** [comment]
https://github.com/TheCheatsrichter/Gw2_Launchbuddy/releases/tag/2.3.8 should be fixed with this release.

Profile concept got noted down! Requires some major code overhauls but might should be considered if LB popularity increases again.

**Comment by hansyulian** [comment]
hello, i tried the 2.3.9 and i still get the same problem

**Comment by ChiefAkela** [comment]
Got the same issue and have for over like 2 months. Have tried it with current version when I launched today. 
Deleted all profiles. 
Closed program. 
Reopened. 
Made two new accounts.
Set each with their seperate login.
Test the first one and it has the second login file
Test second one, and it has the second (correct) login file
I have deleted everything for gw2launchbuddy in APPDATA as well to give it a clean install and it still happens. I have no idea what to do right now.

**Comment by mriot** [comment]
Just confirming that I still have this problem on 2.4.1. 
Creating individual accounts (without cloning) works perfectly.

**Comment by WolfSabian** [comment]
This issue still exists in 2.4.2 despite it being listed as fixed in update notes.

**Comment by TheCheatsrichter** [comment]
@WolfSabian please consider that cloned account created before 2.4.2 might still suffer from this issue. Could you please test it on a freshly cloned account and post the results here?

**Comment by WolfSabian** [comment]
> @WolfSabian please consider that cloned account created before 2.4.2 might still suffer from this issue. Could you please test it on a freshly cloned account and post the results here? 

It was a new clone of an existing account, done with 2.4.2.  what can I provide that you need? I will test again. But I expect the same result.

**Comment by WolfSabian** [comment]
I just tested and can confirm it's still an issue. Setting log in of cloned account changes the login info of the original. Also, changing the info of the original back, changes the clone.

**Comment by FoolMeOnce** [comment]
I have found a solution and a possible cause for why this is happening.

When an account is cloned, the clone is given a new `ID` but uses the original profile's `AccountID`

Here's an example from `Accs.xml`:
```xml
  <Account>
    <ID>12</ID>
    <Nickname>Alt Gen 6</Nickname>
    <Settings>
      <AccountID>10</AccountID>
      <Arguments>
        <Argument>
```

To fix this, you need to completely close Launchbuddy and manually edit `Accs.xml` in `%AppData%\Roaming\Gw2 Launchbuddy\`
**Back up `Accs.xml` first before messing with it!**

Make sure each account has its own `ID` and `AccountID`, I don't know if they need to match:
```xml
  <Account>
    <ID>12</ID>
    <Nickname>Alt Gen 6</Nickname>
    <Settings>
      <AccountID>12</AccountID>
      <Arguments>
        <Argument>
```

**Comment by TheCheatsrichter** [comment]
Fix pushed with
https://github.com/TheCheatsrichter/Gw2_Launchbuddy/commit/ea527da47614bad952eaa716f0c6be11c405746f

will be included in next release
